import type { Job } from '@/lib/types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    companyName: 'Innovate Inc.',
    location: 'San Francisco, CA',
    postedDate: '2 days ago',
    salary: '$120,000 - $160,000',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    profileMatchScore: 92,
  },
  {
    id: '2',
    title: 'UX/UI Designer',
    companyName: 'Creative Solutions',
    location: 'New York, NY',
    postedDate: '5 days ago',
    salary: '$90,000 - $110,000',
    skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research'],
    profileMatchScore: 88,
  },
  {
    id: '3',
    title: 'Backend Engineer (Python)',
    companyName: 'DataDriven Co.',
    location: 'Austin, TX (Remote)',
    postedDate: '1 week ago',
    salary: '$130,000 - $170,000',
    skills: ['Python', 'Django', 'PostgreSQL', 'AWS'],
    profileMatchScore: 95,
  },
  {
    id: '4',
    title: 'Product Manager',
    companyName: 'NextGen Apps',
    location: 'Seattle, WA',
    postedDate: '3 days ago',
    salary: '$140,000 - $180,000',
    skills: ['Agile', 'Roadmap Planning', 'User Stories', 'Market Analysis'],
    profileMatchScore: 85,
  },
    {
    id: '5',
    title: 'Data Scientist',
    companyName: 'QuantumLeap AI',
    location: 'Boston, MA',
    postedDate: '1 day ago',
    salary: '$150,000 - $190,000',
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'SQL'],
    profileMatchScore: 98,
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    companyName: 'CloudSphere',
    location: 'Remote',
    postedDate: '10 days ago',
    salary: '$110,000 - $150,000',
    skills: ['Kubernetes', 'Docker', 'CI/CD', 'Terraform'],
    profileMatchScore: 90,
  },
  {
    id: '7',
    title: 'Junior Web Developer',
    companyName: 'Web Weavers',
    location: 'Chicago, IL',
    postedDate: '4 days ago',
    salary: '$70,000 - $90,000',
    skills: ['HTML', 'CSS', 'JavaScript', 'jQuery'],
    profileMatchScore: 78,
  },
  {
    id: '8',
    title: 'Mobile App Developer (iOS)',
    companyName: 'Apptivate',
    location: 'Los Angeles, CA',
    postedDate: '6 days ago',
    salary: '$100,000 - $140,000',
    skills: ['Swift', 'UIKit', 'CoreData', 'Xcode'],
    profileMatchScore: 89,
  },
];
